main: com.wostenberg.minecraft.playergreeter.PlayerGreeterPlugin
name: PlayerGreeter
version: 0.1
api-version: 1.16
author: Jwosty
commands:
  reload:
    description: Reloads PlayerGreeter config
    useage: /playergreeter:<command>
    permission: playergreeter.reload
permissions:
  playergreeter.reload:
    default: op